"""Controlled clinical vocabulary for symptom descriptions, plus a many-to-
many link so one check-in's free text can normalize to several terms.

Revision ID: 0028
Revises: 0027
"""

from alembic import op
import sqlalchemy as sa


revision = "0028"
down_revision = "0027"
branch_labels = None
depends_on = None

# Starter vocabulary so the AI classifier has real terms to reuse from day
# one instead of inventing a fresh label for every early check-in — it can
# still add new terms when nothing here fits.
SEED_TERMS = [
    "Cefaleia",
    "Febre",
    "Tosse",
    "Coriza",
    "Dor de garganta",
    "Congestão nasal",
    "Falta de ar",
    "Dor no peito",
    "Palpitações",
    "Náusea",
    "Vômito",
    "Diarreia",
    "Constipação",
    "Dor abdominal",
    "Refluxo",
    "Perda de apetite",
    "Dor lombar",
    "Dor articular",
    "Dor muscular",
    "Fadiga",
    "Tontura",
    "Insônia",
    "Sonolência excessiva",
    "Ansiedade",
    "Irritabilidade",
    "Alteração de humor",
    "Erupção cutânea",
    "Coceira na pele",
    "Ressecamento da pele",
    "Inchaço",
    "Dor nos olhos",
    "Vermelhidão ocular",
    "Visão turva",
    "Zumbido",
    "Dor de ouvido",
    "Sangramento",
    "Febre baixa",
    "Calafrios",
    "Suor noturno",
    "Perda de peso",
]


def upgrade() -> None:
    op.create_table(
        "symptom_terms",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("uq_symptom_terms_label_lower", "symptom_terms", [sa.text("lower(label)")], unique=True)
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON symptom_terms TO healthy_agent_api")
    op.execute("GRANT USAGE, SELECT ON SEQUENCE symptom_terms_id_seq TO healthy_agent_api")

    op.execute("ALTER TABLE symptom_terms ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE symptom_terms FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        -- Just a shared clinical vocabulary (term labels), no patient data —
        -- readable by any authenticated request (same idiom as roles_select
        -- in 0009); only the normalization service ever writes to it.
        CREATE POLICY symptom_terms_select ON symptom_terms FOR SELECT USING (
            app_private.service_context() OR app_private.current_supabase_user_id() IS NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE POLICY symptom_terms_write ON symptom_terms FOR ALL
            USING (app_private.service_context())
            WITH CHECK (app_private.service_context())
        """
    )

    symptom_terms = sa.table(
        "symptom_terms",
        sa.column("label", sa.String()),
    )
    op.bulk_insert(symptom_terms, [{"label": label} for label in SEED_TERMS])

    op.create_table(
        "daily_report_symptom_terms",
        sa.Column("daily_report_id", sa.Integer(), sa.ForeignKey("daily_reports.id", ondelete="CASCADE"), nullable=False),
        sa.Column("symptom_term_id", sa.Integer(), sa.ForeignKey("symptom_terms.id", ondelete="CASCADE"), nullable=False),
        # Denormalized from daily_reports.user_id so RLS can check patient
        # access directly, matching clinical_attachments' pattern (0013).
        sa.Column("patient_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.PrimaryKeyConstraint("daily_report_id", "symptom_term_id", name="pk_daily_report_symptom_terms"),
    )
    op.create_index("ix_daily_report_symptom_terms_patient", "daily_report_symptom_terms", ["patient_id"])
    op.create_index("ix_daily_report_symptom_terms_term", "daily_report_symptom_terms", ["symptom_term_id"])
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON daily_report_symptom_terms TO healthy_agent_api")

    op.execute("ALTER TABLE daily_report_symptom_terms ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE daily_report_symptom_terms FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY daily_report_symptom_terms_select ON daily_report_symptom_terms FOR SELECT USING (
            app_private.service_context() OR app_private.can_access_patient(patient_id)
        )
        """
    )
    op.execute(
        """
        -- Entirely system-generated by the AI classifier — never written
        -- directly by a patient or professional.
        CREATE POLICY daily_report_symptom_terms_write ON daily_report_symptom_terms FOR ALL
            USING (app_private.service_context())
            WITH CHECK (app_private.service_context())
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS daily_report_symptom_terms_select ON daily_report_symptom_terms")
    op.execute("DROP POLICY IF EXISTS daily_report_symptom_terms_write ON daily_report_symptom_terms")
    op.drop_table("daily_report_symptom_terms")

    op.execute("DROP POLICY IF EXISTS symptom_terms_select ON symptom_terms")
    op.execute("DROP POLICY IF EXISTS symptom_terms_write ON symptom_terms")
    op.drop_table("symptom_terms")
