"""sync refresh_tokens model

Revision ID: 1521f5a0b14b
Revises: f2952a27b9ce
Create Date: 2026-01-27 02:23:51.431937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1521f5a0b14b'
down_revision: Union[str, None] = 'f2952a27b9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
