"""check

Revision ID: 1bd887ae5859
Revises: 1521f5a0b14b
Create Date: 2026-02-13 03:21:19.686350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bd887ae5859'
down_revision: Union[str, None] = '1521f5a0b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('awaiting_daily_response', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_daily_prompt_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'last_daily_prompt_at')
    op.drop_column('users', 'awaiting_daily_response')
    # ### end Alembic commands ###
